---

  - name: install needed packages
    apt:  name={{ item }} state=present update_cache=yes
    with_items:
      - apache2
      - mysql-server
      - php5
      - libapache2-mod-php5
      - python-mysqldb
      - php5-mysql

  - name: update mysql root password
    mysql_user: name=root host={{ item }} password={{ mysql_root_password }}
    with_items:
      - $ansible_hostname
      - 127.0.0.1
      - ::1
      - localhost

  - name: copy my.cnf file to server
    template: src=my.cnf.j2 dest=~/.my.cnf


  - name: create mysql database for wordpress
    mysql_db: name=wordpress state=present login_user=root login_password={{ mysql_root_password }}

  - name: create mysql user for wordpress
    mysql_user: >
                name=wordpress 
                password={{ wordpress_password }} 
                priv=*.*:ALL
                login_password={{ mysql_root_password }} 
                login_user=root
                state=present

  - name: set perms on /var/www/html
    file: dest=/var/www/html state=directory mode=755 owner=www-data group=www-data

  - name: download wordpress files
    get_url: url=https://wordpress.org/latest.tar.gz dest=/var/www/html/wordpress.tar.gz

  - name: inflate the contents of the wordpress archive
    unarchive: src=/var/www/html/wordpress.tar.gz dest=/var/www/html group=www-data owner=www-data copy=no

  - name: replace wordpress config with template
    template: src=wp-config.php.j2 dest=/var/www/html/wordpress/wp-config.php
