---

  - name: install needed packages
    apt:  name={{ item }} state=present update_cache=yes
    with_items:
      - apache2
      - mysql-common
      - php5
      - libapache2-mod-php5

  - name: update mysql root password
    mysql_user: name=root host={{ item }} password={{ mysql_root_password }}
    with_items:
      - $ansible_hostname
      - 127.0.0.1
      - ::1
      - localhost

  - name: create mysql database for wordpress
    mysql_db: name=wordpress state=present login_user=root login_password={{ mysql_root_password }}

  - name: create mysql user for wordpress
    mysql_user: >
                name=wordpress 
                password={{ wordpress_password }} 
                priv=*.*:ALL
                login_password={{ mysql_root_password }} 
                login_user=root
                state=present

  - name: download wordpress files
    get_url:

  - name: inflate the contents of the wordpress archive
    unarchive: 

  - name: replace wordpress config with template
    template:




# vim:ft=ansible:
